server:
  address:0.0.0.0
  port:8080

logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    probes:
      enabled: true
    livenessState:
      enabled: true
    readinessState:
      enabled: true




authorName: Vikram Gupta
